// Code generated by gop (Go+); DO NOT EDIT.

package main

import (
	"golang.org/lsptests/overload/a"
	"golang.org/lsptests/overload/b"
	"golang.org/lsptests/overload/c"
	"golang.org/lsptests/overload/d"
)
